server:
  port: 8082
spring:
  application:
     name: user-service # Change to your microservice name
  datasource:
    url: jdbc:mysql://localhost:3306/skillprodb # Replace `your_database_name` with your DB name
    username: root # Replace with your MySQL username
    password: 8900 # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use `create`, `update`, or `none` based on your requirements
    show-sql: true # Shows SQL queries in the logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Use MySQL5Dialect for older versions



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


